import assert from 'node:assert/strict';
import fs from 'node:fs';
const js = fs.readFileSync(new URL('../public/js/builds.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../public/builds.css', import.meta.url), 'utf8');
assert.match(js, /suggestTeamSubstitutions/);
assert.match(js, /suggestAlternativeLineups/);
assert.match(js, /Roster alternatives/);
assert.match(js, /Exact one-slot source swap/);
assert.match(js, /data-lineup-preview/);
assert.match(js, /NEW TEAM PREVIEW/);
assert.match(js, /BEST OWNED/);
assert.match(css, /\.team-replacements\s*\{/);
assert.match(css, /\.replacement-option--verified/);
assert.match(css, /\.alternative-lineup--playable/);
assert.match(css, /\.lineup-preview\s*\{/);
console.log('Build substitution UI tests passed');
